"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt
from functools import reduce


def factorize(n, factors):
    for x in range(2, int(sqrt(n)) + 1):
        if n % x == 0:
            factors[x] = factors.get(x, 1) + 1
            return factorize(n // x, factors)
    factors[n] = factors.get(n, 1) + 1
    return factors


triangle = 1
i = 2

while reduce(lambda x, y: x * y, factorize(triangle, {}).values()) < 500:
    triangle += i
    i += 1

print(triangle)
